version: '3.8'

services:


  backend:
    image: videoflix-backend
    build:
      context: ../Videoflix-Backend
    ports:
      - "8080:8080" # Passe ggf. den Backend-Port an
    environment:
      - NODE_ENV=production
    networks:
      - videoflix-net

  frontend:
    image: videoflix-frontend
    build:
      context: ../Videoflix-Frontend
    ports:
      - "3000:3000" # Passe ggf. den Frontend-Port an
    environment:
      - VITE_API_URL=http://backend:8080
    networks:
      - videoflix-net

  networks:
    videoflix-net:
      driver: bridge


  db:
    image: postgres:latest
    container_name: videoflix_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: videoflix_redis
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    container_name: videoflix_backend

    volumes:
      - .:/app
      - videoflix_media:/app/media
      - videoflix_static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis




volumes:
  postgres_data:
  redis_data:
  videoflix_media:
  videoflix_static:
