# Generated by Django 5.2.3 on 2025-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_120p',
            field=models.FileField(blank=True, null=True, upload_to='videos/120p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_360p',
            field=models.FileField(blank=True, null=True, upload_to='videos/360p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p/'),
        ),
    ]
