# Generated by Django 5.2.3 on 2025-07-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_watchprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_120p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_360p',
        ),
        migrations.AddField(
            model_name='video',
            name='video_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos/480p/'),
        ),
    ]
