# Generated by Django 5.2.3 on 2025-07-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_remove_video_video_120p_remove_video_video_360p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_1080p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_480p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_720p',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/originals/'),
        ),
    ]
